name: Docker CI/CD

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron:  '0 4 * * *'

env:
  IMAGE_NAME: sts-backend

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run: |
          rm .dockerignore
          docker build . --file Dockerfile --tag test
          docker run -e "TOMTOM_API_KEY=${{ secrets.TOMTOM_API_KEY }}" -e "BIGDATACLOUD_API_KEY=${{ secrets.BIGDATACLOUD_API_KEY }}" -e "CI=true" -e "HEALTH_CHECK_TOKEN=${{ secrets.HEALTH_CHECK_TOKEN }}" -e "RATE_LIMIT_MAX=${{ secrets.RATE_LIMIT_MAX }}" -e "RATE_LIMIT_TIME_WINDOW=${{ secrets.RATE_LIMIT_TIME_WINDOW }}" --entrypoint sh test -c "npm ci && npm test"

  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/davidsarkany/sts-backend:latest
          platforms: linux/amd64,linux/arm64
